# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUmlLmdnVIu1vdqI8QucsJehsOsNA5qu
"""

# Install dan load package yang diperlukan
if (!requireNamespace("psych", quietly = TRUE)) install.packages("psych")
if (!requireNamespace("GPArotation", quietly = TRUE)) install.packages("GPArotation")

library(psych)
library(GPArotation)

# Data
X1 <- c(98,103,103,105,109,123,123,133,133,133,134,136,138,138,141,147,149,153,155,155,158,159,162,177)
X2 <- c(81,84,86,86,88,92,95,99,102,102,100,102,98,99,105,108,107,107,115,117,115,118,124,132)
X3 <- c(38,38,42,42,44,50,46,51,51,51,48,49,51,51,53,57,55,56,63,60,62,63,61,67)

data <- data.frame(X1, X2, X3)

# 1. Uji KMO
kmo_result <- KMO(data)
cat("🔹 Hasil Uji KMO:\n")
print(kmo_result)

# 2. Uji Bartlett
bartlett_result <- cortest.bartlett(cor(data), n = nrow(data))
cat("\n🔹 Hasil Uji Bartlett:\n")
print(bartlett_result)

# 3. MSA (Measure of Sampling Adequacy)
msa_result <- kmo_result$MSA
cat("\n🔹 Hasil MSA (Measure of Sampling Adequacy):\n")
print(msa_result)

# Data
X1 <- c(98,103,103,105,109,123,123,133,133,133,134,136,138,138,141,147,149,153,155,155,158,159,162,177)
X2 <- c(81,84,86,86,88,92,95,99,102,102,100,102,98,99,105,108,107,107,115,117,115,118,124,132)
X3 <- c(38,38,42,42,44,50,46,51,51,51,48,49,51,51,53,57,55,56,63,60,62,63,61,67)

y1 <- log(X1)
y2 <- log(X2)
y3 <- log(X3)
y <- data.frame(y1,y2,y3)
Y <- y[10:20,]
fit_pca <- princomp(Y, cor=FALSE)
summary(fit_pca)
loadings(fit_pca)
plot(fit_pca, type="lines")
fit_pca$scores